// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.UTMCoordinateConverter
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("conversion")]
        public string Conversion { get; set; }

        [JsonProperty("input")]
        public Input Input { get; set; }

        [JsonProperty("output")]
        public Output Output { get; set; }

        [JsonProperty("formatted")]
        public string Formatted { get; set; }

        [JsonProperty("datum")]
        public string Datum { get; set; }
    }

    public partial class Input
    {
        [JsonProperty("latitude")]
        public double Latitude { get; set; }

        [JsonProperty("longitude")]
        public double Longitude { get; set; }
    }

    public partial class Output
    {
        [JsonProperty("zone")]
        public long Zone { get; set; }

        [JsonProperty("hemisphere")]
        public string Hemisphere { get; set; }

        [JsonProperty("easting")]
        public double Easting { get; set; }

        [JsonProperty("northing")]
        public long Northing { get; set; }
    }
}
